### ISSUE TITLE
Cannot run the app from the source code

### ISSUE THREAD

**Issue by huntertran** [serum-390/soen390-team16-godzilla#105]
Missing database connection.
There is no instruction for the database in wiki or readme.

![image](https://user-images.githubusercontent.com/4468525/108081379-e6f48580-703e-11eb-96e7-d5e94524dc8b.png)

**Comment by instamine** [comment]
We are currently investigating this issue.

**Comment by obonobo** [comment]
Hi @huntertran, we added a PostgreSQL database to the project which Spring tries to connect to on boot. I still need to update the docs, but you can spin up the database (along with pgadmin - a web gui for postgres):

In root directory of project:
```bash
# Spin up postgres on localhost:5432, pgadmin on localhost:3500
docker-compose up -d

# Run the app
mvn spring-boot:run

# Or you can build the entire thing with one script
cd docker/
./build-and-run.sh
```

**Comment by obonobo** [comment]
With an available database, the app can pass its tests

**Comment by huntertran** [comment]
I think you misunderstood the purpose of docker. Docker is born to resolve the number 1 reason of developer: "It works on my machine"

It means that when you are in development, docker should not be used, but in the deployment phase.

That's being said, you should not mix the development environment with the database hosted in docker and the source code hosted on your real machine.

**Comment by obonobo** [comment]
@huntertran, I'm not sure I follow. We *are* using Docker to solve "it works on my machine". 

The database that we are running in docker is a development database, we are not using Docker for deployment. Actually, we are only using Docker as a development tool in the project; the app gets deployed to AWS ECS (which runs the containers in Containerd - not Docker), and our cloud database is on AWS RDS. So we are not really using Docker anywhere except on dev machine and on the CI/CD.

It is very convenient developing with a docker database because you can destroy it any time and spin up a fresh db. 

Actually, the app doesn't need a docker db to run; it just needs *any* Postgres db to connect to - if you have a local installation of Postgres, it will work with this app (it needs a database named "godzilla" present in Postgres). 

**Can you clarify what your suggestion is here? What is your desired behavior?**

As I see it, there are only really 2 ways for us to run a development DB: native installation, and docker. Of those 2 options, docker db for development is much more convenient.

Currently, the app will try to connect to its db and if it fails, then the app fails to run. So the best option seems to be to develop with a local dev database running in docker.

The only alternative I see would be to add a feature to the app where it will create its own database (like an in-memory sql database using [H2](https://www.h2database.com/html/main.html)) if it fails to connect to Postgres. This would be nice for running tests, but even the CI is spinning up a postgres docker container to run tests so this feature is not 100% necessary. Plus, we would not want the app to have this feature on the ECS cluster (on ECS, it is better if the app fails than creates its own db) - this means we would have to add more configuration so that this feature doesnt exist in production.

**What would be your recommended setup for development?**

**Comment by huntertran** [comment]
Ah I see, you can quickly destroy the docker container and spin up a new container from your pre-built image right?

> Actually, the app doesn't need a docker db to run; it just needs any Postgres db to connect to - if you have a local installation of Postgres, it will work with this app (it needs a database named "godzilla" present in Postgres).

This is the information I need. You should list this in `Prerequisites`

**Comment by huntertran** [comment]
I follow this instruction and got errors: https://github.com/serum-390/soen390-team16-godzilla/wiki

Cleary the database installation is not mentioned

**Comment by obonobo** [comment]
> 
> 
> Ah I see, you can quickly destroy the docker container and spin up a new container from your pre-built image right?
> 
> > Actually, the app doesn't need a docker db to run; it just needs any Postgres db to connect to - if you have a local installation of Postgres, it will work with this app (it needs a database named "godzilla" present in Postgres).
> 
> This is the information I need. You should list this in `Prerequisites`

Yes, exactly. The app depends on having a DB, so it will fail if it can't connect (which is what it looks happened in your original post).

For development, I would rather give people 1 docker command that they can run to spin up a Postgres container configured properly for our app. This is better than going through and manually installing postgres on everyone's machine, which quickly leads to the *"it was working fine on my machine!"* problem, and then having to debug everyone's individual postgres configs and versions, etc.

You are right, I must have missed updating that wiki page, my bad. We made a wiki page for the db: <https://github.com/serum-390/soen390-team16-godzilla/wiki/Docker:-Postgres-Setup>

And I added the instructions to the README.md:
![image](https://user-images.githubusercontent.com/52555183/109712138-a8e28000-7b6d-11eb-90c8-aa5d9312316b.png)

but I forgot the wiki page you mentioned, sorry. It should work if you run those two commands above (one command to run the db, one command to run the app). Make sure to pull the latest docker image for our app first: `docker pull ghcr.io/serum-390/godzilla`

**Comment by obonobo** [comment]
I'll give that wiki page you mentioned an update

**Comment by obonobo** [comment]
Alright, I updated that wiki page with the correct instructions.

btw, there is a shell script that can be used to do everything in one command (spin up DB, run mvn package, build docker image, and run docker container):

```bash
cd docker/
./build-and-run.sh
```

I didnt document this just because it was a quick and dirty script I wrote, and it is only a few commands anyways to run everything. You may have to remove the line 8 from the script, it reads `set -e` and will error out the script if you don't already have a godzilla container.
